# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ModelerSearchEnhancer
                                 A QGIS plugin
 Advanced search functionality for QGIS Processing Modeler algorithms and parameters
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-07-29
        copyright            : (C) 2025 by GIS Team
        email                : gis@eagleprojects.it
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ModelerSearchEnhancer class from file ModelerSearchEnhancer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .modeler_search_enhancer import ModelerSearchEnhancer
    return ModelerSearchEnhancer(iface)
